# Generated by Django 4.2.1 on 2023-05-16 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='speed',
            field=models.FloatField(default=0),
        ),
    ]
