# Generated by Django 4.2.1 on 2023-05-22 20:19

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0003_fieldagents'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FieldAgents',
            new_name='Agents',
        ),
    ]
