# Generated by Django 4.2.1 on 2023-05-26 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_obstacle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obstacle',
            name='status',
            field=models.CharField(choices=[('Fixed', 'Fixed'), ('Pending', 'Pending')], default='Pending', null=True),
        ),
    ]
