# Generated by Django 4.2.1 on 2023-05-26 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_obstacle_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obstacle',
            name='image',
            field=models.ImageField(null=True, upload_to='obstacle_images/'),
        ),
    ]
