# Generated by Django 4.2.1 on 2023-06-03 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obstacle',
            name='reported_by',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
