# Generated by Django 4.2.1 on 2023-06-04 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_obstacle_reported_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_type', models.CharField(choices=[('Signal Failure', 'Signal Failure'), ('Track Obstruction', 'Track Obstruction'), ('Equipment Malfunction', 'Equipment Malfunction'), ('Emergency Situation', 'Emergency Situation')], max_length=50)),
                ('incident_description', models.TextField()),
                ('incident_date', models.DateTimeField()),
                ('reported_by', models.CharField(max_length=100, null=True)),
                ('location', models.CharField(max_length=100, null=True)),
                ('vehicle_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.vehicle')),
            ],
        ),
    ]
