# Generated by Django 4.2.1 on 2023-06-04 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_incident'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incident',
            old_name='incident_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='incident',
            old_name='incident_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='incident',
            old_name='incident_type',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='incident',
            old_name='vehicle_number',
            new_name='vehicle',
        ),
    ]
