# Generated by Django 4.2.1 on 2023-06-04 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_rename_incident_date_incident_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='type',
            field=models.CharField(choices=[('Fire', 'Fire'), ('Collision', 'Collision'), ('Signal Failure', 'Signal Failure'), ('Track Obstruction', 'Track Obstruction'), ('Vandalism', 'Vandalism'), ('Equipment Malfunction', 'Equipment Malfunction'), ('Emergency Situation', 'Emergency Situation')], max_length=50),
        ),
    ]
