# Generated by Django 4.2.1 on 2023-06-04 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_incident_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='status',
            field=models.CharField(choices=[('Fixed', 'Fixed'), ('Pending', 'Pending')], default='Pending', null=True),
        ),
    ]
