# Generated by Django 4.2.1 on 2023-06-05 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_maintenance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maintenance',
            old_name='maintenance_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='maintenance',
            old_name='maintenance_type',
            new_name='type',
        ),
    ]
