# Generated by Django 4.2.1 on 2023-06-05 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Status',
            new_name='StatusV',
        ),
    ]
