# Generated by Django 4.2.1 on 2023-06-09 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obstacle',
            name='status',
            field=models.CharField(choices=[('Fixed', 'Fixed'), ('Pending', 'Pending')], null=True),
        ),
    ]
