# Generated by Django 4.2.1 on 2023-06-09 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_alter_obstacle_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='status',
            field=models.CharField(choices=[('Fixed', 'Fixed'), ('Pending', 'Pending')], null=True),
        ),
    ]
