# Generated by Django 4.2.1 on 2023-06-11 12:19

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_rename_description_profile_adress_profile_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='users',
        ),
        migrations.AddField(
            model_name='team',
            name='user1',
            field=models.CharField(null=True, verbose_name=django.contrib.auth.models.User),
        ),
        migrations.AddField(
            model_name='team',
            name='user2',
            field=models.CharField(null=True, verbose_name=django.contrib.auth.models.User),
        ),
        migrations.AddField(
            model_name='team',
            name='user3',
            field=models.CharField(null=True, verbose_name=django.contrib.auth.models.User),
        ),
    ]
