# Generated by Django 4.2.1 on 2023-06-11 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_remove_team_users_team_user1_team_user2_team_user3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='user1',
        ),
        migrations.RemoveField(
            model_name='team',
            name='user2',
        ),
        migrations.RemoveField(
            model_name='team',
            name='user3',
        ),
        migrations.AddField(
            model_name='team',
            name='users',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.vehicle'),
        ),
    ]
